language: python
python:
  - "3.7"
  - "3.8"
  - "3.9-dev"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest --cov-report term --cov=motioneye_client
after_success:
  - codecov --env TRAVIS_OS_NAME
